import React from 'react';
import { Sparkles, ShieldAlert, Cpu, Database, CheckCircle2, X } from 'lucide-react';

export default function AiDisclaimerBanner({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fadeIn">
      <div className="glass-modal max-w-2xl w-full rounded-2xl p-6 border border-slate-700 shadow-2xl relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 border-b border-slate-800 pb-4 mb-4">
          <div className="p-3 rounded-xl bg-blue-500/20 text-blue-400 border border-blue-500/30">
            <Sparkles className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              AI Market Research & Valuation Methodology
            </h3>
            <p className="text-xs text-slate-400">
              Generated & Synthesized by AI Equity Market Quantitative Models
            </p>
          </div>
        </div>

        <div className="space-y-4 text-xs md:text-sm text-slate-300">
          <div className="p-3 bg-blue-950/40 border border-blue-500/30 rounded-xl flex items-start gap-3">
            <Cpu className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
            <div>
              <h4 className="font-semibold text-blue-300 mb-1">AI Synthesis Architecture</h4>
              <p className="text-slate-300 text-xs leading-relaxed">
                The Equity Market Valuation Index and per-country market research reports are synthesized in real-time by multi-agent financial LLMs. The engine ingests fundamental metrics (Shiller CAPE, Trailing P/E, Forward P/E, P/B, Dividend Yield, and Buffett Indicator) alongside IMF macro updates.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
            <div className="p-3 bg-slate-900/80 rounded-xl border border-slate-800">
              <div className="flex items-center gap-2 font-semibold text-emerald-400 mb-1">
                <Database className="w-4 h-4" />
                Data Inputs Monitored
              </div>
              <ul className="text-slate-400 space-y-1 text-[11px] list-disc list-inside">
                <li>Shiller CAPE Ratios (Cyclically Adjusted P/E)</li>
                <li>Consensus Trailing & Forward Earnings</li>
                <li>Nominal GDP & Total Market Capitalization</li>
                <li>Central Bank Interest Rates & Inflation</li>
              </ul>
            </div>

            <div className="p-3 bg-slate-900/80 rounded-xl border border-slate-800">
              <div className="flex items-center gap-2 font-semibold text-amber-400 mb-1">
                <CheckCircle2 className="w-4 h-4" />
                Dynamic Weighting Model
              </div>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                Scores are normalized from 0 (Deep Value) to 100 (Severe Overvaluation). Users can adjust sliders to customize valuation formulas to fit their investment philosophy.
              </p>
            </div>
          </div>

          <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-xl text-amber-200 text-xs flex items-start gap-2.5">
            <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
            <div>
              <h5 className="font-bold text-amber-300 mb-0.5">Financial Research Disclaimer</h5>
              <p className="text-[11px] text-amber-200/90 leading-relaxed">
                Notice: All indices, AI research summaries, scenario projections, and return forecasts are generated by artificial intelligence algorithms for informational, analytical, and research purposes only. They do not constitute financial advice, investment recommendations, or an offer to buy or sell securities.
              </p>
            </div>
          </div>
        </div>

        <div className="mt-6 pt-4 border-t border-slate-800 flex items-center justify-between">
          <span className="text-[10px] font-mono text-slate-500">
            AI Engine Version: ValuaGlobe-v4.2 | Last Synthesis: Sept 2026
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-semibold text-xs transition-colors shadow-lg shadow-blue-500/20"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
}
